Lesson10.c
WIN32_LEAN_AND_MEAN
true
TRUE
Referenced by CreateGLWindow, DrawGLScene, InitGL, KillGLWindow, LoadGLTextures, NeHeLoadBitmap3, WinMain, WndProc.
false
FALSE
Referenced by CreateGLWindow, InitGL, LoadGLTextures, NeHeLoadBitmap3, WinMain, WndProc.
CDS_FULLSCREEN
Referenced by CreateGLWindow.
typedef int bool
typedef struct tagVERTEX VERTEX
typedef struct tagTRIANGLE TRIANGLE
typedef struct tagSECTOR SECTOR
HDC hDC
Referenced by CreateGLWindow, KillGLWindow, WinMain.
HGLRC hRC
Referenced by CreateGLWindow, KillGLWindow.
HWND hWnd
Referenced by CreateGLWindow, KillGLWindow, WndProc.
HINSTANCE hInstance
Referenced by CreateGLWindow, KillGLWindow.
BOOL keys[256][256]
Referenced by WinMain, WndProc.
BOOL active
Referenced by WinMain, WndProc.
BOOL fullscreen
Referenced by CreateGLWindow, KillGLWindow, WinMain.
BOOL blend
Referenced by WinMain.
BOOL bp
Referenced by WinMain.
BOOL fp
Referenced by WinMain.
char* level_debug
Referenced by CreateGLWindow, InitGL, LoadGLTextures, NeHeLoadBitmap3, readstr, SetupWorld, WinMain.
bool level_def
Referenced by CreateGLWindow, InitGL, LoadGLTextures, NeHeLoadBitmap3, readstr, SetupWorld, WinMain.
const float piover180
Referenced by WinMain.
float heading
Referenced by WinMain.
float xpos
Referenced by DrawGLScene, WinMain.
float zpos
Referenced by DrawGLScene, WinMain.
GLfloat yrot
Referenced by DrawGLScene, WinMain.
GLfloat walkbias
Referenced by DrawGLScene, WinMain.
GLfloat walkbiasangle
Referenced by WinMain.
GLfloat lookupdown
Referenced by DrawGLScene, WinMain.
GLfloat z
Referenced by readstr, WinMain.
GLuint filter
Referenced by DrawGLScene, WinMain.
GLuint texture[3][3]
Referenced by DrawGLScene, LoadGLTextures.
GLuint texid[3][3]
Referenced by NeHeLoadBitmap3.
SECTOR sector1
Referenced by DrawGLScene, readstr.
PIXELFORMATDESCRIPTOR pfd
int loop
Referenced by readstr.
int vert
Referenced by readstr.
LRESULT CALLBACK WndProc(HWND hWnd, UINT uMsg, WPARAM wParam, LPARAM lParam)
Fonction CALLBACK de traitement des messages Windows.
Comments manageable by Doxygen Traitement de la boucle infinie des messages Windows hWnd L'header de la fenêtre principale. uMsg Un entier non signé. wParam Les paramétres en entrée. lParam Autres paramétres en entrée. LRESULT Un LRESULT donnant le status du traitement du message.
References active, FALSE, hWnd, keys, ReSizeGLScene, TRUE.
Referenced by CreateGLWindow.
void readstr(char *string)
References level_debug, level_def, log_print, loop, tagSECTOR::numtriangles, sector1, tagSECTOR::triangle, tagVERTEX::u, tagVERTEX::v, vert, tagTRIANGLE::vertex, tagVERTEX::x, tagVERTEX::y, tagVERTEX::z, z.
Referenced by SetupWorld.
void SetupWorld()
References level_debug, level_def, log_print, readstr.
Referenced by InitGL.
bool NeHeLoadBitmap3(LPTSTR szFileName, GLuint *texid)
Fonction NeHeLoadBitmap3 : charge un fichier BMP en mémoire pour generer un tableau de trois textures.
This Code Creates Texture From a Bitmap File. En entrée le nom du fichier Bitmap et en sortie le tableau des trois textures utilisables avec OpenGL szFileName nom du fichier BMP * *texid un pointeur sur lae tableau des trois textures générées * bool un booleen, le tableau des trois textures créé ou non.
References FALSE, level_debug, level_def, log_print, texid, TRUE.
Referenced by LoadGLTextures.
int LoadGLTextures()
References FALSE, level_debug, level_def, log_print, NeHeLoadBitmap3, texture, TRUE.
Referenced by InitGL.
GLvoid ReSizeGLScene(GLsizei width, GLsizei height)
Fonction ReSizeGLScene : redimensionnement de la fenêtre Windows gérant OpenGL.
This Code Resize the main window. En entrée les deux nouvelles dimensions de la fenêtre width Width of the GL Window Or Fullscreen Mode * height Height of the GL Window Or Fullscreen Mode * GLvoid un void OpenGL.
Referenced by CreateGLWindow, WndProc.
int InitGL(GLvoid)
Fonction InitGL : Fin de l'initialisation de la fenêtre Windows gérant OpenGL.
This Code finish the initialization OpenGL of the main window. Rien GLvoid un void OpenGL. int un entier (booleen)
References FALSE, level_debug, level_def, LoadGLTextures, log_print, SetupWorld, TRUE.
Referenced by CreateGLWindow.
int DrawGLScene(GLvoid)
Fonction DrawGLScene : Dessin sous OpenGL dans la fenêtre Windows.
This Code draw the scene OpenGL in the main window. Rien GLvoid un void OpenGL. int un entier (booleen)
References filter, lookupdown, tagSECTOR::numtriangles, sector1, texture, tagSECTOR::triangle, TRUE, tagVERTEX::u, tagVERTEX::v, tagTRIANGLE::vertex, walkbias, tagVERTEX::x, xpos, tagVERTEX::y, yrot, tagVERTEX::z, zpos.
Referenced by WinMain.
GLvoid KillGLWindow(GLvoid)
Fonction KillGLWindow : Destruction de toutes les ressources du programme.
This Code destroy all resources of this program. Rien GLvoid un void OpenGL. GLvoid un void OpenGL.
References fullscreen, hDC, hInstance, hRC, hWnd, TRUE.
Referenced by CreateGLWindow, WinMain.
BOOL CreateGLWindow(char *title, int width, int height, int bits, BOOL fullscreenflag)
Creation of our OpenGL Window.
This Code Creates Our OpenGL Window. Parameters Are: * title - Title To Appear At The Top Of The Window * width - Width Of The GL Window Or Fullscreen Mode * height - Height Of The GL Window Or Fullscreen Mode * bits - Number Of Bits To Use For Color (8/16/24/32) * fullscreenflag - Use Fullscreen Mode (TRUE) Or Windowed Mode (FALSE) * BOOL - un entier booleen (OK ou non).
References CDS_FULLSCREEN, FALSE, fullscreen, hDC, hInstance, hRC, hWnd, InitGL, KillGLWindow, level_debug, level_def, log_print, ReSizeGLScene, TRUE, WndProc.
Referenced by WinMain.
int WINAPI WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nCmdShow)
Creation of our application on Windows System (not console application) *.
This Code is mandatory to create windows application (function WinMain) * hInstance - Header de l'instance Windows * hPrevInstance - Header de l'instance précédente de Windows * lpCmdLine - Un pointeur sur la ligne de commande * nCmdShow - Un indicateur d'état * int - un entier booleen (OK ou non). *
References active, blend, bp, CreateGLWindow, DrawGLScene, FALSE, filter, fp, fullscreen, hDC, heading, keys, KillGLWindow, level_debug, level_def, log_print, lookupdown, piover180, TRUE, walkbias, walkbiasangle, xpos, yrot, z, zpos.