logger.h
void log_print(char *filename, int line, char *fmt,...)
References ft, print_time.
Referenced by CreateGLWindow, InitGL, LoadGLTextures, NeHeLoadBitmap3, readstr, SetupWorld, WinMain.