logger.c
DIR_SEPARATOR
PATH_SEPARATOR
IS_DIR_SEPARATOR
IS_PATH_SEPARATOR
FILE* ft
Referenced by log_print.
int SESSION_TRACKER
char filedir[MAX_PATH][MAX_PATH]
char * print_time()
Referenced by log_print.
void log_print(char *filename, int line, char *fmt,...)
References ft, print_time.
Referenced by CreateGLWindow, InitGL, LoadGLTextures, NeHeLoadBitmap3, readstr, SetupWorld, WinMain.