
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:47 (project)"
    message: |
      The target system is: Windows -  - 
      The host system is: Windows - 10.0.22631 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:47 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.40.33807/bin/Hostx86/x86/cl.exe 
      Build flags: /TC
      Id flags:  
      
      The output was:
      0
      Compilateur d'optimisation Microsoft (R) C/C++ version 19.40.33811 pour x86
      Copyright (C) Microsoft Corporation. Tous droits réservés.
      
      CMakeCCompilerId.c
      Microsoft (R) Incremental Linker Version 14.40.33811.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      /out:CMakeCCompilerId.exe 
      CMakeCCompilerId.obj 
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.obj"
      
      The C compiler identification is MSVC, found in:
        C:/src/OpenGL/NeHe_Lesson10-master/build.cmake/NmakeX32/Release/CMakeFiles/3.29.5/CompilerIdC/CMakeCCompilerId.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:1216 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:250 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:47 (project)"
    message: |
      Detecting C compiler /showIncludes prefix:
        main.c
        Remarque : inclusion du fichier :  C:\\src\\OpenGL\\NeHe_Lesson10-master\\build.cmake\\NmakeX32\\Release\\CMakeFiles\\ShowIncludes\\foo.h
        
      Found prefix "Remarque : inclusion du fichier :  "
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:67 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:47 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/src/OpenGL/NeHe_Lesson10-master/build.cmake/NmakeX32/Release/CMakeFiles/CMakeScratch/TryCompile-7uq9of"
      binary: "C:/src/OpenGL/NeHe_Lesson10-master/build.cmake/NmakeX32/Release/CMakeFiles/CMakeScratch/TryCompile-7uq9of"
    cmakeVariables:
      CMAKE_C_FLAGS: " /TC"
      CMAKE_C_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:X86"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/src/OpenGL/NeHe_Lesson10-master/build.cmake/NmakeX32/Release/CMakeFiles/CMakeScratch/TryCompile-7uq9of'
        
        Run Build Command(s): "C:/Program Files/CMake/bin/cmake.exe" -E env VERBOSE=1 nmake -f Makefile /nologo cmTC_24f89\\fast
        	"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.40.33807\\bin\\Hostx86\\x86\\nmake.exe"  -f CMakeFiles\\cmTC_24f89.dir\\build.make /nologo -L                  CMakeFiles\\cmTC_24f89.dir\\build
        Building C object CMakeFiles/cmTC_24f89.dir/CMakeCCompilerABI.c.obj
        	"C:\\Program Files\\CMake\\bin\\cmake.exe" -E cmake_cl_compile_depends --dep-file=CMakeFiles\\cmTC_24f89.dir\\CMakeCCompilerABI.c.obj.d --working-dir=C:\\src\\OpenGL\\NeHe_Lesson10-master\\build.cmake\\NmakeX32\\Release\\CMakeFiles\\CMakeScratch\\TryCompile-7uq9of --filter-prefix="Remarqueá: inclusion du fichierá:  " -- "C:\\PROGRA~1\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.40.33807\\bin\\Hostx86\\x86\\cl.exe" @C:\\Users\\thier\\AppData\\Local\\Temp\\nm70B5.tmp
        CMakeCCompilerABI.c
        Linking C executable cmTC_24f89.exe
        	"C:\\Program Files\\CMake\\bin\\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\\cmTC_24f89.dir --rc=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\10.0.22621.0\\x86\\rc.exe --mt=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\10.0.22621.0\\x86\\mt.exe --manifests -- "C:\\PROGRA~1\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.40.33807\\bin\\Hostx86\\x86\\link.exe" /nologo @CMakeFiles\\cmTC_24f89.dir\\objects1.rsp @C:\\Users\\thier\\AppData\\Local\\Temp\\nm7104.tmp
        Visual Studio Incremental Link with embedded manifests
        Create CMakeFiles\\cmTC_24f89.dir/manifest.rc
        Create empty: CMakeFiles\\cmTC_24f89.dir/embed.manifest
        RC Pass 1:
        C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\10.0.22621.0\\x86\\rc.exe /fo CMakeFiles\\cmTC_24f89.dir/manifest.res CMakeFiles\\cmTC_24f89.dir/manifest.rc
        LINK Pass 1:
        C:\\PROGRA~1\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.40.33807\\bin\\Hostx86\\x86\\link.exe /nologo @CMakeFiles\\cmTC_24f89.dir\\objects1.rsp /out:cmTC_24f89.exe /implib:cmTC_24f89.lib /pdb:C:\\src\\OpenGL\\NeHe_Lesson10-master\\build.cmake\\NmakeX32\\Release\\CMakeFiles\\CMakeScratch\\TryCompile-7uq9of\\cmTC_24f89.pdb /version:0.0 /machine:X86 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_24f89.dir/intermediate.manifest CMakeFiles\\cmTC_24f89.dir/manifest.res
        MT:
        C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\10.0.22621.0\\x86\\mt.exe /nologo /manifest CMakeFiles\\cmTC_24f89.dir/intermediate.manifest /out:CMakeFiles\\cmTC_24f89.dir/embed.manifest /notify_update
        RC Pass 2:
        C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\10.0.22621.0\\x86\\rc.exe /fo CMakeFiles\\cmTC_24f89.dir/manifest.res CMakeFiles\\cmTC_24f89.dir/manifest.rc
        FINAL LINK:
        C:\\PROGRA~1\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.40.33807\\bin\\Hostx86\\x86\\link.exe /nologo @CMakeFiles\\cmTC_24f89.dir\\objects1.rsp /out:cmTC_24f89.exe /implib:cmTC_24f89.lib /pdb:C:\\src\\OpenGL\\NeHe_Lesson10-master\\build.cmake\\NmakeX32\\Release\\CMakeFiles\\CMakeScratch\\TryCompile-7uq9of\\cmTC_24f89.pdb /version:0.0 /machine:X86 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_24f89.dir/intermediate.manifest CMakeFiles\\cmTC_24f89.dir/manifest.res
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:173 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:47 (project)"
    message: |
      Parsed C implicit link information:
        link line regex: [^( *|.*[/\\])(ld[0-9]*(\\.[a-z]+)?|link\\.exe|lld-link(\\.exe)?|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        linker tool regex: [^[ 	]*(->|")?[ 	]*(([^"]*[/\\])?(ld[0-9]*(\\.[a-z]+)?|link\\.exe|lld-link(\\.exe)?))("|,| |$)]
        linker tool for 'C': C:/PROGRA~1/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.40.33807/bin/Hostx86/x86/link.exe
        implicit libs: []
        implicit objs: []
        implicit dirs: []
        implicit fwks: []
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/Internal/CMakeDetermineLinkerId.cmake:40 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:210 (cmake_determine_linker_id)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:47 (project)"
    message: |
      Running the C compiler's linker: "C:/PROGRA~1/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.40.33807/bin/Hostx86/x86/link.exe" "-v"
      Microsoft (R) Incremental Linker Version 14.40.33811.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
...
