
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:44 (project)"
    message: |
      The target system is: Windows -  - 
      The host system is: Windows - 10.0.22631 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:44 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.40.33807/bin/Hostx86/x86/cl.exe 
      Build flags: /TC
      Id flags:  
      
      The output was:
      0
      Version MSBuild 17.10.4+10fbfbf2e pour .NET Framework
      La g├®n├®ration a d├®marr├® 14/06/2024 16:51:36.
      
      Projet "C:\\src\\OpenGL\\NeHe_Lesson10-master\\build.cmake\\VS2022X32\\CMakeFiles\\3.29.5\\CompilerIdC\\CompilerIdC.vcxproj" sur le n┼ôud 1 (cibles par d├®faut).
      PrepareForBuild:
        Cr├®ation du r├®pertoire "Debug\\".
        La sortie structur├®e est activ├®e. La mise en forme du compilateur diagnostics refl├¿te la hi├®rarchie des erreurs. Pour plus dÔÇÖinformations, consultez https://aka.ms/cpp/structured-output.
        Cr├®ation du r├®pertoire "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        Cr├®ation de "Debug\\CompilerIdC.tlog\\unsuccessfulbuild", car "AlwaysCreate" a ├®t├® sp├®cifi├®.
        Mise ├á jour de l'horodatage "Debug\\CompilerIdC.tlog\\unsuccessfulbuild".
      VcpkgTripletSelection:
        Using triplet "x86-windows" from "C:\\src\\vcpkg\\installed\\x86-windows\\"
        Using normalized configuration "Release"
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.40.33807\\bin\\HostX64\\x86\\CL.exe /c /I"C:\\src\\vcpkg\\installed\\x86-windows\\include" /nologo /W0 /WX- /diagnostics:column /Od /Oy- /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /analyze- /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.40.33807\\bin\\HostX64\\x86\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO /LIBPATH:"C:\\src\\vcpkg\\installed\\x86-windows\\lib" /LIBPATH:"C:\\src\\vcpkg\\installed\\x86-windows\\lib\\manual-link" kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib "C:\\src\\vcpkg\\installed\\x86-windows\\lib\\*.lib" /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X86 /SAFESEH Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> C:\\src\\OpenGL\\NeHe_Lesson10-master\\build.cmake\\VS2022X32\\CMakeFiles\\3.29.5\\CompilerIdC\\CompilerIdC.exe
      AppLocalFromInstalled:
        pwsh.exe -ExecutionPolicy Bypass -noprofile -File "C:\\src\\vcpkg\\scripts\\buildsystems\\msbuild\\applocal.ps1" "C:\\src\\OpenGL\\NeHe_Lesson10-master\\build.cmake\\VS2022X32\\CMakeFiles\\3.29.5\\CompilerIdC\\CompilerIdC.exe" "C:\\src\\vcpkg\\installed\\x86-windows\\bin" "Debug\\CompilerIdC.tlog\\CompilerIdC.write.1u.tlog" "Debug\\vcpkg.applocal.log"
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.40.33807\\bin\\Hostx64\\x86\\cl.exe
      FinalizeBuildStatus:
        Suppression du fichier "Debug\\CompilerIdC.tlog\\unsuccessfulbuild".
        Mise ├á jour de l'horodatage "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate".
      G├®n├®ration du projet "C:\\src\\OpenGL\\NeHe_Lesson10-master\\build.cmake\\VS2022X32\\CMakeFiles\\3.29.5\\CompilerIdC\\CompilerIdC.vcxproj" termin├®e (cibles par d├®faut).
      
      La g├®n├®ration a r├®ussi.
          0 Avertissement(s)
          0 Erreur(s)
      
      Temps ├®coul├® 00:00:01.22
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        C:/src/OpenGL/NeHe_Lesson10-master/build.cmake/VS2022X32/CMakeFiles/3.29.5/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:67 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:44 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/src/OpenGL/NeHe_Lesson10-master/build.cmake/VS2022X32/CMakeFiles/CMakeScratch/TryCompile-ytl327"
      binary: "C:/src/OpenGL/NeHe_Lesson10-master/build.cmake/VS2022X32/CMakeFiles/CMakeScratch/TryCompile-ytl327"
    cmakeVariables:
      CMAKE_C_FLAGS: " /TC"
      CMAKE_C_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:X86"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/src/OpenGL/NeHe_Lesson10-master/build.cmake/VS2022X32/CMakeFiles/CMakeScratch/TryCompile-ytl327'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_b1c55.vcxproj /p:Configuration=Debug /p:Platform=Win32 /p:VisualStudioVersion=17.0 /v:n
        Version MSBuild 17.10.4+10fbfbf2e pour .NET Framework
        La g├®n├®ration a d├®marr├® 14/06/2024 16:51:37.
        
        Projet "C:\\src\\OpenGL\\NeHe_Lesson10-master\\build.cmake\\VS2022X32\\CMakeFiles\\CMakeScratch\\TryCompile-ytl327\\cmTC_b1c55.vcxproj" sur le n┼ôud 1 (cibles par d├®faut).
        PrepareForBuild:
          Cr├®ation du r├®pertoire "cmTC_b1c55.dir\\Debug\\".
          La sortie structur├®e est activ├®e. La mise en forme du compilateur diagnostics refl├¿te la hi├®rarchie des erreurs. Pour plus dÔÇÖinformations, consultez https://aka.ms/cpp/structured-output.
          Cr├®ation du r├®pertoire "C:\\src\\OpenGL\\NeHe_Lesson10-master\\build.cmake\\VS2022X32\\CMakeFiles\\CMakeScratch\\TryCompile-ytl327\\Debug\\".
          Cr├®ation du r├®pertoire "cmTC_b1c55.dir\\Debug\\cmTC_b1c55.tlog\\".
        InitializeBuildStatus:
          Cr├®ation de "cmTC_b1c55.dir\\Debug\\cmTC_b1c55.tlog\\unsuccessfulbuild", car "AlwaysCreate" a ├®t├® sp├®cifi├®.
          Mise ├á jour de l'horodatage "cmTC_b1c55.dir\\Debug\\cmTC_b1c55.tlog\\unsuccessfulbuild".
        VcpkgTripletSelection:
          Using triplet "x86-windows" from "C:\\src\\vcpkg\\installed\\x86-windows\\"
          Using normalized configuration "Release"
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.40.33807\\bin\\HostX64\\x86\\CL.exe /c /I"C:\\src\\vcpkg\\installed\\x86-windows\\include" /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /Oy- /D _MBCS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_b1c55.dir\\Debug\\\\" /Fd"cmTC_b1c55.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TC /analyze- /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.29\\Modules\\CMakeCCompilerABI.c"
          Compilateur d'optimisation Microsoft (R) C/C++ version┬á19.40.33811 pour x86
          Copyright (C) Microsoft Corporation. Tous droits r├®serv├®s.
          cl /c /I"C:\\src\\vcpkg\\installed\\x86-windows\\include" /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /Oy- /D _MBCS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_b1c55.dir\\Debug\\\\" /Fd"cmTC_b1c55.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TC /analyze- /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.29\\Modules\\CMakeCCompilerABI.c"
          CMakeCCompilerABI.c
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.40.33807\\bin\\HostX64\\x86\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\src\\OpenGL\\NeHe_Lesson10-master\\build.cmake\\VS2022X32\\CMakeFiles\\CMakeScratch\\TryCompile-ytl327\\Debug\\cmTC_b1c55.exe" /INCREMENTAL /ILK:"cmTC_b1c55.dir\\Debug\\cmTC_b1c55.ilk" /NOLOGO /LIBPATH:"C:\\src\\vcpkg\\installed\\x86-windows\\lib" /LIBPATH:"C:\\src\\vcpkg\\installed\\x86-windows\\lib\\manual-link" kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib "C:\\src\\vcpkg\\installed\\x86-windows\\lib\\*.lib" /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/src/OpenGL/NeHe_Lesson10-master/build.cmake/VS2022X32/CMakeFiles/CMakeScratch/TryCompile-ytl327/Debug/cmTC_b1c55.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/src/OpenGL/NeHe_Lesson10-master/build.cmake/VS2022X32/CMakeFiles/CMakeScratch/TryCompile-ytl327/Debug/cmTC_b1c55.lib" /MACHINE:X86 /SAFESEH  /machine:X86 cmTC_b1c55.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_b1c55.vcxproj -> C:\\src\\OpenGL\\NeHe_Lesson10-master\\build.cmake\\VS2022X32\\CMakeFiles\\CMakeScratch\\TryCompile-ytl327\\Debug\\cmTC_b1c55.exe
        AppLocalFromInstalled:
          pwsh.exe -ExecutionPolicy Bypass -noprofile -File "C:\\src\\vcpkg\\scripts\\buildsystems\\msbuild\\applocal.ps1" "C:\\src\\OpenGL\\NeHe_Lesson10-master\\build.cmake\\VS2022X32\\CMakeFiles\\CMakeScratch\\TryCompile-ytl327\\Debug\\cmTC_b1c55.exe" "C:\\src\\vcpkg\\installed\\x86-windows\\bin" "cmTC_b1c55.dir\\Debug\\cmTC_b1c55.tlog\\cmTC_b1c55.write.1u.tlog" "cmTC_b1c55.dir\\Debug\\vcpkg.applocal.log"
        FinalizeBuildStatus:
          Suppression du fichier "cmTC_b1c55.dir\\Debug\\cmTC_b1c55.tlog\\unsuccessfulbuild".
          Mise ├á jour de l'horodatage "cmTC_b1c55.dir\\Debug\\cmTC_b1c55.tlog\\cmTC_b1c55.lastbuildstate".
        G├®n├®ration du projet "C:\\src\\OpenGL\\NeHe_Lesson10-master\\build.cmake\\VS2022X32\\CMakeFiles\\CMakeScratch\\TryCompile-ytl327\\cmTC_b1c55.vcxproj" termin├®e (cibles par d├®faut).
        
        La g├®n├®ration a r├®ussi.
            0 Avertissement(s)
            0 Erreur(s)
        
        Temps ├®coul├® 00:00:01.12
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:173 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:44 (project)"
    message: |
      Parsed C implicit link information:
        link line regex: [^( *|.*[/\\])(ld[0-9]*(\\.[a-z]+)?|link\\.exe|lld-link(\\.exe)?|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        linker tool regex: [^[ 	]*(->|")?[ 	]*(([^"]*[/\\])?(ld[0-9]*(\\.[a-z]+)?|link\\.exe|lld-link(\\.exe)?))("|,| |$)]
        linker tool for 'C': C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.40.33807/bin/HostX64/x86/link.exe
        implicit libs: []
        implicit objs: []
        implicit dirs: []
        implicit fwks: []
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/Internal/CMakeDetermineLinkerId.cmake:40 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:210 (cmake_determine_linker_id)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:44 (project)"
    message: |
      Running the C compiler's linker: "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.40.33807/bin/HostX64/x86/link.exe" "-v"
      Microsoft (R) Incremental Linker Version 14.40.33811.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
...
